Vector to random points
Open-EO/openeo-processes-python pull request #97
Opened 2022-03-08 16:55 UTC by clausmichele

Here is my implementation of vector_to_random_points.
I've tried to include all the edge cases but there are still a couple of things to add, see the TODO in the code.

Sample code to test the implementation:

```
import openeo_processes as oeop

data = {
  'type': 'FeatureCollection',
  'features': [
    {
      'type': 'Feature',
      'properties': {},
      'geometry': {
        'type': 'Polygon',
        'coordinates': [
            [
              [
                11.12417221069336,
                46.09228143052647
              ],
              [
                11.171035766601562,
                46.09228143052647
              ],
              [
                11.171035766601562,
                46.11525271077457
              ],
              [
                11.12417221069336,
                46.11525271077457
              ],
              [
                11.12417221069336,
                46.09228143052647
              ]
            ]
        ]
      }
    },
    {
      'type': 'Feature',
      'properties': {},
      'geometry': {
        'type': 'MultiPolygon',
        'coordinates': [
          [
          [
            [
              11.14614486694336,
              46.06215432178359
            ],
            [
              11.16382598876953,
              46.06215432178359
            ],
            [
              11.16382598876953,
              46.069419674968515
            ],
            [
              11.14614486694336,
              46.069419674968515
            ],
            [
              11.14614486694336,
              46.06215432178359
            ]
          ]
          ],
          [
          [
            [
              11.1676025390625,
              46.06155875862966
            ],
            [
              11.186313629150389,
              46.06155875862966
            ],
            [
              11.186313629150389,
              46.068824190192196
            ],
            [
              11.1676025390625,
              46.068824190192196
            ],
            [
              11.1676025390625,
              46.06155875862966
            ]
          ]
          ]
        ]
      }
    },
    {
      'type': 'Feature',
      'properties': {},
      'geometry': {
        'type': 'Point',
        'coordinates': [
          11.124343872070312,
          46.059176441769665
        ]
      }
    },
    {
      'type': 'Feature',
      'properties': {},
      'geometry': {
        'type': 'Point',
        'coordinates': [
          11.132755279541016,
          46.072039731663025
        ]
      }
    }
  ]
}
points = oeop.vector_to_random_points(data,seed=None,geometry_count=10)

print(points.to_json())
```

2022-03-09 15:52 UTC, LukeWeidenwalker commented
Thanks - will aim to provide a review by EOD tomorrow!

2022-03-10 11:17 UTC, ValentinaHutter commented on src/openeo_processes/arrays.py
> +                    count += 1
If the Point is not in the geometry, you would instead just add the point in the center of the geometry, but shouldn't it always be possible to find a random Point inside a Polygon?

2022-03-10 11:42 UTC, LukeWeidenwalker requested changes
Nice - I've left a few comments above, but the overall structure looks really good to me!

I know you're already aware of this, but thought I'd mention it here again: 
@soxofaan mentions the shapely representative_point function in the [other thread](https://github.com/Open-EO/openeo-processes/pull/315#issuecomment-1063031313) - I haven't had time to test it out yet, but this sounds quite promising indeed.

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for feature in data['features']:
Is this really necessary? I just tried removing the properties field from the sample data you've provided and commented out this block and the result is unchanged!

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for feature in data['features']:
Is this really necessary? I just tried removing the properties field from the sample data you've provided and commented out this block and the result is unchanged!

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for feature in data['features']:
Is this really necessary? I just tried removing the properties field from the sample data you've provided and commented out this block and the result is unchanged!

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for idx, polygon in multipolygons_gdf.iterrows():
In the current form the logic in this loop is exactly the same as the loop for Polygons above - @clausmichele are you aware of any edgecase handling that wants to be different for Polygons/Multipolygons? Otherwise I'd suggest folding this into one loop to save some lines of code!

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for idx, polygon in multipolygons_gdf.iterrows():
In the current form the logic in this loop is exactly the same as the loop for Polygons above - @clausmichele are you aware of any edgecase handling that wants to be different for Polygons/Multipolygons? Otherwise I'd suggest folding this into one loop to save some lines of code!

2022-03-10 11:42 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for idx, polygon in multipolygons_gdf.iterrows():
In the current form the logic in this loop is exactly the same as the loop for Polygons above - @clausmichele are you aware of any edgecase handling that wants to be different for Polygons/Multipolygons? Otherwise I'd suggest folding this into one loop to save some lines of code!

2022-03-10 11:59 UTC, clausmichele commented on src/openeo_processes/arrays.py
> +                    count += 1
In theory yes, but how much time would it take? With complex geometries it's not obvious to easily find points within them. You can try to define a complex geometry by yourself using geojson.io and see.

2022-03-10 12:17 UTC, clausmichele commented on src/openeo_processes/arrays.py
> +        for feature in data['features']:
Thanks for pointing this out. Actually I've also forgot to check if the property is None. I'll add it now.

It is related to this geopandas bug. I've opened a PR for that https://github.com/geopandas/geopandas/pull/2243

- If the geoJSON is valid (every geometry has a property field) and the properties are not `null` -> no problems
- If the geoJSON is valid (every geometry has a property field) and one property is `null` -> geopandas error
- If the geoJSON is missing a property field -> geopandas error

So the code is solving the second and third scenarios.

2022-03-10 12:21 UTC, clausmichele commented on src/openeo_processes/arrays.py
> +        for feature in data['features']:
You can try the code again with my latest commit.

If you set one property to None in the Python dict and you comment that part, you'll get an error.

2022-03-11 09:49 UTC, LukeWeidenwalker commented on src/openeo_processes/arrays.py
> +        for idx, polygon in multipolygons_gdf.iterrows():
Ah, yes, I understand that, I meant that specifically the point-generation loops for the Polygons (ln1780-1815) and then the MultiPolygons (ln1818-1856) seem to be doing the exact same thing, so couldn't we do something like this?

```suggestion
        for idx, polygon in pd.concat(polygons_gdf, multipolygons_gdf).iterrows():
```

More of a nitpick though!

2022-03-15 17:37 UTC, LukeWeidenwalker commented
@clausmichele 
> I'm completely overwhelmed by this PR and can't really follow the status any longer.
Quoting Matthias from the other thread - I feel very much the same.

I'd propose we:
- merge this in as it is, because it does what it advertises. I'm happy with it already, we don't have to resolve my nitpick comment right now
- create a new issue to investigate using the shapely representative_point function instead in the future
- follow the new tickets around how this process needs to change in the future and write tests once the requirements are more stable 

Quick thumbs-up would be appreciated!

2022-03-16 08:05 UTC, clausmichele commented
Let's merge it first, we'll try to follow the new proposals later on!

2022-03-16 08:59 UTC, merged